#!/bin/sh
ABSPATH="/home/xdroid/mcm/city-data/visual"

while [ ! -z "$1" ]
do
    file=`basename $1 .coutput`
    echo "Dealing with $file..."

    cat "$file.coutput" | tr -d '\15\32' | awk -F ' ' -E "$ABSPATH/lib/p.awk" | sed -e 's#\(.*\),$#[\1]#g' > "$file.json"
    node "$ABSPATH/lib/render.js" "$file.json"
    shift
done
